### ISSUE TITLE
Worker Process Recycle Events should is beeping but not corelating

### ISSUE THREAD

**Issue by aspaan** [ShekharGupta1988/AppLensV2#204] opened 2016-12-21 05:52 UTC
https://applensv2.azurewebsites.net/sites/ilivingapp/detectors/workerprocessrecycle?startTime=2016-12-20

**Comment by ShekharGupta1988** [comment] 2016-12-21 18:16
The reason for that is "worker process restart" is a umbrella detector. 
We only correlate umbrella detectors when no high priority detectors gets correlated to reduce noise and redundancy.

In this case, If you notice, user did a site restart. So User Initiated site restart detector got correlated. Now this activity would cause worker process restart as well. But it doesn't make sense to correlate that as its a result of user restarting the site.

**Comment by ShekharGupta1988** [comment] 2016-12-21 18:35
@aspaan - feel free to close the issue if this is convincing. Otherwise, we can discuss in person.

**Comment by andreyse** [comment] 2016-12-22 00:12
Shekhar you are right - it is by design from beginning

**Closed** 2016-12-22 17:42 UTC
Labels: bug, ready
