### ISSUE TITLE
PROD : PerfMon Detector: Site not found exception

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#210] opened 2016-12-23 01:28 UTC
https://applensv2.azurewebsites.net/sites/jet.com/detectors/garbagecollectiongen2

Looks like geomaster call to get perfmon data is throwing site not found error.

**Comment by stevenernst131** [comment] 2016-12-23 20:02
Looks like the Resource group we are getting does not match observer, which is causing the call to the geomaster to fail, specifically in a site not found error.  All I am doing is using the subscription and webspace name to call Aspaan’s resource group observer API so I think there might be a bug because the subscription and webspace name are correct. Not sure why it is working for some and not others.

 
![image](https://cloud.githubusercontent.com/assets/7739017/21461582/ad0fea4a-c907-11e6-8dd2-43d32c73d08a.png)

**Comment by ShekharGupta1988** [comment] 2016-12-28 01:48
This will affect Migration detector tool also.

**Comment by ShekharGupta1988** [comment] 2016-12-28 17:29
Tagging this as PROD. 
One of the internal customer faced this problem too.

DiagnosticRole | where RequestId == "g-ad044f5f-dcb2-4a3c-b9f1-d52aa8f1bfcf"

**Comment by aspaan** [comment] 2016-12-28 21:05
Not a bug. The ability to chose a admin site should take care of this issue

**Comment by ShekharGupta1988** [comment] 2016-12-29 23:12
This is not completely fixed.
Still not working:
https://applensv2.azurewebsites.net/sites/jet.com/detectors/garbagecollectiongen2

The new API needs to be called in AppLensV2 to fix the issue.

**Comment by stevenernst131** [comment] 2017-01-03 19:08
#212 fix checked in to call new api

**Closed** 2017-01-03 19:09 UTC
Labels: imp
