### ISSUE TITLE
please check if this is ASEV1 and the detector is not applicable for this case?

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#950] opened 2018-01-18 23:31 UTC
We need to understand why the detector is saying storage health is 0 for the whole day. Behavior or bug?

Current site: https://applensv2.azurewebsites.net/sites/ospdirectoriesapp-prod/appanalysis/detectors/storagehealth?startTime=2018-01-16T02:00:00.000Z&endTime=2018-01-16T04:00:00.000Z 

Applens does not provide any Storage Health info for this App– blade always shows 0 availability.  Not sure if this is an ASEv2 limitation.

**Comment by hforeste** [comment] 2018-03-08 19:41
Closing this issue since its duplicate of #939

**Closed by hforeste** 2018-03-08 19:41 UTC
