### ISSUE TITLE
IE/Edge doesn't display charts data

### ISSUE THREAD

**Issue by cristhianu** [ShekharGupta1988/AppLensV2#122] opened 2016-11-10 16:36 UTC
When looking at the charts on any of the detectors in IE/Edge, it shows all the data in 0 whereas looking at the same data in Chrome shows the correct data.
![detectorscharts-ie-edge-vs-chrome](https://cloud.githubusercontent.com/assets/7376302/20185399/87584bf0-a731-11e6-9bf4-10783c2a716a.jpg)

**Comment by ShekharGupta1988** [comment] 2017-01-05 22:32
marking this as duplicate of https://github.com/ShekharGupta1988/AppLensV2/issues/87

**Closed by ShekharGupta1988** 2017-01-05 22:32 UTC
